### ISSUE TITLE
subject line is unreadable

### ISSUE THREAD

**Issue by ittayd** [stadler/SendPage#9] opened 2015-12-16 09:27 UTC
When I send a page (this time a random google search page), the subject is unreadable: '=?utf-8?B?aGl2ZSB0ZW1wb3JhcnkgdGFibGUgLSBHb29nbGUgU2VhcmNo?='

This started happening recently (maybe after the last update) and is happening in all sites.

My email client is Outlook 2013

**Comment by stadler** [comment] 2015-12-22 22:12
Hey thanks for the report.
There seems to have been some regression since the last version.
It should now be fixed in version 1.8. Let me know if you encounter more issues.

**Closed by stadler** 2015-12-22 22:12 UTC
